library(shiny)

shinyUI(pageWithSidebar(
  headerPanel("Height Estimator"),
  sidebarPanel(
    selectInput("gender",
                label = h3("Your Gender:"),
                list("Male" = "male",
                     "Female" = "female")),

    numericInput("childNum",
                 label = h3("Your Birth Order:"),
                 value = 1, min = 1),
    
    numericInput("mother",
                 label = h3("Height of Mother:"),
                 value = 65),

    numericInput("father",
               label = h3("Height of Father:"),
               value = 69),
    
    actionButton("goButton", "Estimate Me!")
    
    ),
  
    mainPanel(
      tabsetPanel(
        tabPanel(h3("Estimator"),        
                h3('Your Estimated Height:'),
                textOutput('height'),
                conditionalPanel(
                  condition="input.goButton > 0",
                  h3('95% Confidence Interval'),
                  h4('Lower'),
                  textOutput('confidenceLower'),
                  h4('Upper'),
                  textOutput('confidenceUpper'))),
        
        tabPanel(h3("Directions"),
                 p("Enter your data into the side panel controls, and then click 'Estimate Me!'.  
                   The results will show up on the estimator tab."),
                 h4("Your Gender"),
                 p("Select your biological gender."),
                 h4("Your Birth Order"),
                 p("Select your birth order.  If you are the oldest child of your parents
                   select 1, second oldest select 2.  When in doubt, make your best guess!"),
                 h4("Height of Mother"),
                 p("Height of your biological mother in inches."),
                 h4("Height of Father"),
                 p("Height of your biological father in inches")),
        
        tabPanel(h3("Methodology"),
                 p("The model used for this application was generated by doing a basic linear 
                   regression on the dataset GaltonFamilies in the HistData library of R."),
                 p("The model was saved to a file, so that the computation would not have to be 
                   run each time a query was made.  The downside of this is that we can't train the
                   model further based on actual inputs."),
                 p("Future work if this were to be continued might include taking feedback from 
                   users about their actual height, and using that to adjust the model as we went along
                   to reflect more current data."))
        ))
))